version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.11
  pre_build:
    on-failure: ABORT
    commands:
      - echo Pre-Build phase ran on `date`
  build:
    on-failure: ABORT
    commands:
      - echo Build phase started on `date`
      - env
      - echo Build phase completed on `date`
  post_build:
    on-failure: ABORT
    commands:
      - echo Post-Build ran on `date`
